EmilienG/LibrairieFusion-v1.0

- build/web/css/moncss.css
- web/css/moncss.css
rajout de background repeat : no-repeat
> Modification css body

- src/java/controleurs/ControllerMain.java
> commentaires

- nbproject/private/private.properties
- web/WEB-INF/catalogue.jsp
les images sont redimentionnées en %
> taille image ok

- web/WEB-INF/catalogue.jsp
- web/WEB-INF/menus/menu-main.jsp
- web/css/moncss.css
> Branch silicium

- web/WEB-INF/catalogue.jsp
- web/css/moncss.css
> Branch cobalt

- nbproject/private/private.properties
- src/java/accesBDD/EvenementDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/obj/Evenement.java
- web/WEB-INF/Evenement.jsp
alors j'ai fait du lourd , pool moi ca man !
> Branch wiss03

- src/java/controleurs/ControllerMain.java
evenement ok.
reste à a faire : coup de coeur 
reste à faire : inscription
> modif 05/03 09:45

- src/java/accesBDD/EvenementDAO.java
- src/java/controleurs/ControllerMain.java
> fix evenement

- src/java/accesBDD/LivresDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/obj/Livres.java
- web/WEB-INF/catalogue.jsp
- web/WEB-INF/compte.jsp
- web/WEB-INF/inscription.jsp
- web/WEB-INF/panier.jsp
> idLivre pour addPanier

- nbproject/private/private.properties
- src/java/accesBDD/CompteDAO.java
- src/java/accesBDD/EvenementDAO.java
- src/java/accesBDD/LivresDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/obj/Client.java
- src/java/traitements/GestionCompte.java
- src/java/traitements/GestionLivres.java
- web/WEB-INF/inscription.jsp
> dernier modif

- src/java/accesBDD/ClientDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/obj/Client.java
- src/java/traitements/GestionClients.java
- web/WEB-INF/compte.jsp
- web/WEB-INF/home.jsp
- web/WEB-INF/menus/menu-main.jsp
- web/css/moncss.css
> ajout compte modif methods client

- nbproject/private/private.properties
- nbproject/private/private.xml
- web/WEB-INF/inscription.jsp
> meregggggeeeeeeeeeeeeeeeeeeee

- nbproject/private/private.properties
- nbproject/private/private.xml
- src/java/accesBDD/ClientDAO.java
- src/java/accesBDD/CoupDeCoeurDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/traitements/GestionClients.java
- src/java/traitements/GestionLogin.java
- web/WEB-INF/catalogue.jsp
- web/WEB-INF/compte.jsp
> fix login pseudo Identiques

- src/java/accesBDD/CompteDAO.java
- src/java/accesBDD/CoupDeCoeurDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/traitements/GestionCompte.java
- web/WEB-INF/CoupDeCoeur.jsp
- web/WEB-INF/Evenement.jsp
- web/WEB-INF/inscription.jsp
- web/css/moncss.css
> creation compte ok bug commande

- nbproject/private/private.properties
- src/java/controleurs/ControllerMain.java
- web/WEB-INF/CoupDeCoeur.jsp
> ajout Recherche coup de coeur et On Rentre a la Maison

- nbproject/private/private.properties
- src/java/controleurs/ControllerMain.java
- src/java/traitements/GestionClients.java
- web/WEB-INF/compte.jsp
> fix bug compte

- src/java/accesBDD/CompteDAO.java
- src/java/controleurs/ControllerMain.java
- web/WEB-INF/compte.jsp
- web/WEB-INF/menus/menu-main.jsp
reste bug info qui disparaissent
Faire ca
puis ca
et enfin ca
> fix modif compte

- src/java/accesBDD/LivresDAO.java
- src/java/controleurs/ControllerMain.java
- src/java/traitements/GestionLivres.java
- web/WEB-INF/catalogue.jsp
- web/WEB-INF/details.jsp
- web/WEB-INF/panier.jsp
> Super mewto

- nbproject/private/private.properties
- nbproject/private/private.xml
- src/java/accesBDD/CoupDeCoeurDAO.java
- src/java/accesBDD/EvenementDAO.java
- src/java/obj/Evenement.java
- web/WEB-INF/CoupDeCoeur.jsp
- web/WEB-INF/Evenement.jsp
> Branchwiss3.0

- nbproject/private/private.properties
- nbproject/private/private.xml
- src/java/controleurs/ControllerMain.java
- web/WEB-INF/catalogue.jsp
- web/WEB-INF/inscription.jsp
- web/WEB-INF/jspLogin.jsp
- web/WEB-INF/menus/footer.jsp
- web/WEB-INF/panier.jsp
- web/css/moncss.css
> artikodin vole
